# Generated by Django 2.2.1 on 2019-07-08 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDetail',
            fields=[
                ('academic_id', models.AutoField(primary_key=True, serialize=False)),
                ('highschool_detail', models.TextField()),
                ('intermediate_detail', models.TextField()),
                ('academic_activities', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('contact_number', models.IntegerField()),
                ('location', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('academic_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='castapp.AcademicDetail')),
            ],
        ),
    ]
